accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import logout
# from django.contrib import admin

urlpatterns = [
    url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url
from lists import views
# from django.contrib import admin

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as accounts_urls
# from django.contrib import admin

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(accounts_urls)),
]

accounts/models.py
from django.db import models
import uuid
from django.contrib import auth

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
	'''пользователь'''
	email = models.EmailField(primary_key=True)
	REQUIRED_FIELDS = []
	USERNAME_FIELD = 'email'
	is_anonymous = False 
	is_authenticated = True
# Create your models here.

class Token(models.Model):
	'''маркер'''
	email = models.EmailField()
	uid = models.CharField(default=uuid.uuid4,max_length=40)

lists/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):
	''' список '''
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
	def get_absolute_url(self):
		'''получить абсолютный url'''
		return reverse('view_list', args=[self.id])
	
	@property
	def name(self):
		'''имя'''
		return self.item_set.first().text

class Item(models.Model):
	'''элемент списка'''
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

	class Meta:
		ordering = ('id',)
		unique_together = ('list', 'text')

	def __str__(self):
		return self.text

	

lists/forms.py
from django import forms
from lists.models import Item
from django.core.exceptions import ValidationError

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already go this in your list"

class ItemForm(forms.models.ModelForm):
	'''форма для элемента списка'''

	class Meta:
		model = Item
		fields = ('text',)
		widgets = {
			'text': forms.fields.TextInput(attrs={
				'placeholder': 'Enter a to-do item',
				'class': 'form-control input-lg',
			}),
		}
		error_messages = {
			'text': {'required': EMPTY_ITEM_ERROR}
		}

	def save(self, for_list):
		self.instance.list = for_list
		return super().save()

class ExistingListItemForm(ItemForm):
	'''форма для элемента существующего списка'''
	def __init__(self, for_list, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.instance.list = for_list

	def validate_unique(self):
		'''проверка уникальности'''
		try:
			self.instance.validate_unique()
		except ValidationError as e:
			e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
			self._update_errors(e)

	def save(self):
		return forms.models.ModelForm.save(self)

accounts/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.contrib import auth, messages
from accounts.models import Token
from django.core.urlresolvers import reverse

def send_login_email(request):
	'''отправить сообщение для входа в систему'''
	email = request.POST['email']
	token = Token.objects.create(email=email)
	url = request.build_absolute_uri(
		reverse('login') + '?token=' + str(token.uid)
	)
	message_body = f'Use this link to log in:\n\n{url}'
	send_mail(
		'Your login link for Superlists',
		message_body,
		'noreplay@superlists',
		[email],
	)
	messages.success(
		request,
		"Проверте свою почту, мы отправили Вам ссылку, \
которую можно использовать для входа на сайт."
	)
	return redirect('/')

def login(request):
	''' логирование пользователя'''
	user = auth.authenticate(uid=request.GET.get('token'))
	if user:
		auth.login(request, user)
	return redirect('/')

lists/views.py
from django.contrib.auth import get_user_model
User = get_user_model()
from django.core.exceptions import ValidationError
from django.shortcuts import render,redirect
from lists.forms import ItemForm
from lists.models import Item, List
from lists.forms import ExistingListItemForm, ItemForm, NewListForm

# Create your views here.
def home_page(request):
	'''домашняя страница'''
	return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, list_id):
	'''представление списка'''
	list_ = List.objects.get(id=list_id)
	form = ExistingListItemForm(for_list=list_)
	if request.method == 'POST':
		form = ExistingListItemForm(for_list=list_, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect(list_)
	return render(request, 'list.html', {'list': list_, "form":form})

def new_list(request):
	'''новый список'''
	form = NewListForm(data=request.POST)
	if form.is_valid():
		list_ = form.save(owner=request.user)
		return redirect(list_)
	return render(request, 'home.html', {'form': form})

def my_lists(request, email):
	'''мои списки'''
	owner = User.objects.get(email=email)
	return render(request, 'my_lists.html', {'owner': owner})

accounts/templates/login_email_sent.html
<html>
	<h1>Email sent</h1>

	<p>Check your email, you'll find a massage with a link that will log you into the site.</p>
	
</html>

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>To-Do lists</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/base.css">
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
				<a href="/" class="navbar-brand">Superlists</a>
				{% if user.email %}
					<ul class="nav navbar-nav navbar-left">
						<li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="navbar-text">Logged in as {{ user.email }}</li>
						<li><a href="{% url 'logout' %}">Log out</a></li>
					</ul>
				{% else %}
					<form action="{% url 'send_login_email' %}" method="POST" class="navbar-form navbar-rigth">
						<span>Enter email to log in:</span>
						<input type="text" class="form-control" name="email">
						{% csrf_token %}
					</form>
				{% endif %}
			</div>
		</nav>
		{% if messages %}
			<div class="row">
				<div class="col-md-8">
					{% for message in messages %}
						{% if message.level_tag == 'seccess' %}
							<div class="alert alert-success">{{ message }}</div>
						{% else %}
							<div class="alert alert-warnning">{{ message }}</div>
						{% endif %}
					{% endfor %}
				</div>
			</div>
		{% endif %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 jumbotron">
				<div class="text-center">
					<h1>{% block header_text %}{% endblock %}</h1>
					{% block list_form %}
					<form method="POST" action="{% block form_action %}{% endblock %}">
						{{ form.text }}
						{% csrf_token %}
						{% if form.errors %}
							<div class="form-group has-error">
								<span class="help-block">{{ form.text.errors }}</span>
							</div>
						{% endif %}
					</form>
					{% endblock %}
				</div>
			</div>
		</div>
	
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				{% block table%}
				{% endblock %}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				{% block extra_content %}
				{% endblock %}
			</div>
		</div>
	</div>
	<script src="/static/jquery-3.4.1.min.js"></script>
	<script src="/static/list.js"></script>

	<script>
		$(document).ready(function(){
			window.Superlists.initialize();
		});
	</script>
	
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table%}
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}
{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email}}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}